import Footer from "@components/Footer";
import Navbar from "@components/Navbar";
import "@styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    
    <html lang="en" className="scroll-smooth focus:scroll-auto">
      
      <body className="text-sm main">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
